//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Practice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [DisplayName("Mã Nhà Xuất Bản: ")]
        public int MaNXB { get; set; }
        [DisplayName("Tên Nhà Xuất Bản: ")]
        public string TenNXB { get; set; }
        [DisplayName("Thông Tin: ")]
        public string ThongTin { get; set; }
        public string Logo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
