//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Practice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }

        [DisplayName("Mã sản phẩm: ")]
        public int MaSP { get; set; }
        [DisplayName("Tên sản phẩm: ")]
        public string TenSP { get; set; }
        [DisplayName("Đơn giá:")]
        public Nullable<decimal> DonGia { get; set; }
        [DisplayName("Ngày cập nhật: ")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [DisplayName("Mô tả: ")]
        public string MoTa { get; set; }
        [DisplayName("Ảnh sản phẩm: ")]
        public string HinhAnh { get; set; }
        [DisplayName("Số lượng tồn: ")]
        public Nullable<int> SoLuongTon { get; set; }
        [DisplayName("Lượt xem: ")]
        public Nullable<int> LuotXem { get; set; }
        [DisplayName("Lượt bình chọn: ")]
        public Nullable<int> LuotBinhChon { get; set; }
        [DisplayName("Lượt bình luận: ")]
        public Nullable<int> LuotBinhLuan { get; set; }
        [DisplayName("Lần mua: ")]
        public Nullable<int> SoLanMua { get; set; }
        [DisplayName("Tình trạng mới: ")]
        public Nullable<int> Moi { get; set; }
        [DisplayName("Mã truyện: ")]
        public Nullable<int> MaTruyen { get; set; }
        [DisplayName("Mã NXB: ")]
        public Nullable<int> MaNXB { get; set; }
        [DisplayName("Mã NCC: ")]
        public Nullable<int> MaNCC { get; set; }
        [DisplayName("Mã Loại SP: ")]
        public Nullable<int> MaLoaiSP { get; set; }
        [DisplayName("Đã xóa: ")]
        public Nullable<bool> DaXoa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
