//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Practice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [DisplayName("Mã Truyện: ")]
        public int MaTruyen { get; set; }
        [DisplayName("Tên Truyện: ")]
        public string TenTruyen { get; set; }
        [DisplayName("Mã Loại SP: ")]
        public Nullable<int> MaLoaiSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
